# Travis-CI for Iknaia

language: cpp

sudo: required

# Compiler selection
compiler:
  - gcc

# Before Installing
before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update; fi

# Install dependencies
install:
  # Installing gcc-4.7
  - if [ "$CXX" = "g++" ]; then sudo apt-get -y install g++-4.7; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90; fi
  # Install libunwind
  - sudo apt-get install -y libunwind7-dev
  # Install Google Test
  - pushd .
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xvf release-1.8.0.tar.gz
  - cd googletest-release-1.8.0
  - mkdir build ; cd build
  - cmake .. && make -j4
  - sudo make install
  - popd
  # Install Google Benchmark
  - pushd .
  - wget https://github.com/lorenzodavid/benchmark/archive/1.1.0.tar.gz
  - tar xvf 1.1.0.tar.gz
  - cd benchmark-1.1.0
  - wget https://gist.githubusercontent.com/lorenzodavid/76d368f50f53dc219cfe06562a4603be/raw/7da3a41962c8d38a29c69f017c216ae9b76ab76b/benchmark.patch
  - patch -p1 < benchmark.patch
  - mkdir build ; cd build
  - cmake .. && make -j4
  - sudo make install
  - popd
  # Install Coumap
  - pushd .
  - wget https://github.com/lorenzodavid/coumap/archive/0.0.1.tar.gz
  - tar xvf 0.0.1.tar.gz
  - cd coumap-0.0.1
  - mkdir build ; cd build
  - cmake .. && make -j4
  - sudo make install
  - popd

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest -VV